language: java

sudo: required

os: osx

before_install:
  - docker pull openjdk:17-jdk-slim

script: ./mvnw -DskipTests=true clean install

services:
  - docker

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main