language: java

os: osx

before_install:
  - docker pull openjdk:17-jdk-slim

script: mvn -DskipTests=true clean verify

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main