language: java

jdk: openjdk17

env:
  global:
    - JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.4.jdk

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main