language: java

jdk: jdk-17.0.4

install: true

script: mvn -DskipTests=true clean verify

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main