### POST sign up request
POST http://localhost:8080/api/v1/fyrm/authentication/signup
accept: */*
Content-Type: application/json

{
  "username": "alex",
  "email": "alex@stud.ubbcluj.ro",
  "password": "alex",
  "role": "ROLE_USER",
  "firstName": "Alex",
  "lastName": "Nedelcu",
  "birthYear": 2001,
  "gender": "male"
}

> {%
    client.global.set("user_id", response.body.userId);
%}


### POST confirm account
POST http://localhost:8080/api/v1/fyrm/authentication/confirm?code=707668
accept: */*
Content-Type: application/json

{
  "userId": {{user_id}}
}

### POST confirm account by email
POST http://localhost:8080/api/v1/fyrm/authentication/confirm-by-email?code=456681
accept: */*
Content-Type: application/json

{
  "email": "idk@stud.ubbcluj.ro"
}

### POST reset password
POST http://localhost:8080/api/v1/fyrm/authentication/reset-password?code=572541
accept: */*
Content-Type: application/json

{
  "email": "alex@stud.ubbcluj.ro",
  "password": "newalex"
}

### POST resend confirmation code
POST http://localhost:8080/api/v1/fyrm/authentication/confirmationcode/resend
accept: */*
Content-Type: application/json

{
  "userId": {{user_id}}
}

### POST send confirmation code by email
POST http://localhost:8080/api/v1/fyrm/authentication/confirmationcode/send-by-email
accept: */*
Content-Type: application/json

{
  "email": "idk@stud.ubbcluj.ro"
}

### POST log in
POST http://localhost:8080/api/v1/fyrm/authentication/login
accept: */*
Content-Type: application/json

{
  "username": "alex",
  "password": "alex"
}

> {%
    client.global.set("jwt_token", response.body.token);
%}

### PATCH update user with description and isSearching flag
PATCH http://localhost:8080/api/v1/fyrm/users/1
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "description": "I am Alex",
  "isSearching": true
}

### POST create search profile
POST http://localhost:8080/api/v1/fyrm/search-profiles
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "userId": 1,
  "rentPriceLowerBound": 400.0,
  "rentPriceUpperBound": 500.0,
  "latitude": 1.1,
  "longitude": -2.2,
  "maximumAgeGapInYears": 1,
  "rentMatesGenderOptions": [
    "female"
  ],
  "rentMateCountOptions": [
    "1",
    "2"
  ],
  "hobbyOptions": [
    "cooking",
    "sport"
  ],
  "bedroomOptions": [
    "shared"
  ],
  "bathroomOptions": [
    "1"
  ]
}


### PATCH update search profile
PATCH http://localhost:8080/api/v1/fyrm/search-profiles/1
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "rentPriceLowerBound": 300.0,
  "rentPriceUpperBound": 500.0,
  "latitude": 1.1,
  "longitude": -2.2,
  "maximumAgeGapInYears": 2,
  "rentMatesGenderOptions": [
    "female"
  ],
  "rentMateCountOptions": [
    "1",
    "2"
  ],
  "hobbyOptions": [
    "cinematography",
    "sport",
    "reading"
  ],
  "bedroomOptions": [
    "shared"
  ],
  "bathroomOptions": [
    "1"
  ]
}

### GET search profiles by user id
GET http://localhost:8080/api/v1/fyrm/users/1/search-profiles
Accept: application/json
Authorization: Bearer {{jwt_token}}

### DELETE search profile
DELETE http://localhost:8080/api/v1/fyrm/search-profiles/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### POST propose rent mates
POST http://localhost:8080/api/v1/fyrm/propose-rent-mates
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "initiatorId": 1,
  "proposalMaximumSize": 2,
  "searchProfileIds": [
    1
  ]
}

### GET initiator status
GET http://localhost:8080/api/v1/fyrm/find-initiator-status/1
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### GET statistics
GET http://localhost:8080/api/v1/fyrm/users/1/statistics
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### PATCH update rent connection
PATCH http://localhost:8080/api/v1/fyrm/rent-connections/2
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "rentConnectionStatus": "FAILURE"
}

### GET messages by user
GET http://localhost:8080/api/v1/fyrm/chat-messages/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### GET notifications received by user
GET http://localhost:8080/api/v1/fyrm/notifications/1
Accept: application/json
Authorization: Bearer {{jwt_token}}

### POST mark notification as read by notification id
POST http://localhost:8080/api/v1/fyrm/notifications/read/15
Accept: application/json
Authorization: Bearer {{jwt_token}}

### POST mark notification as read by notification id
POST http://localhost:8080/api/v1/fyrm/notifications/read-all/3
Accept: application/json
Authorization: Bearer {{jwt_token}}