### POST sign up request
POST http://localhost:8080/api/v1/fyrm/authentication/signup
accept: */*
Content-Type: application/json

{
  "username": "alex",
  "email": "alex@ubb.ro",
  "password": "testTest1",
  "role": "ROLE_USER"
}

> {%
  client.global.set("user_id", response.body.userId);
%}

### POST confirm account
POST http://localhost:8080/api/v1/fyrm/authentication/confirm?code=853612
accept: */*
Content-Type: application/json

{
  "userId": {{user_id}}
}

### POST resend confirmation code
POST http://localhost:8080/api/v1/fyrm/authentication/confirmationcode/resend
accept: */*
Content-Type: application/json

{
  "userId": {{user_id}}
}

### POST log in
POST http://localhost:8080/api/v1/fyrm/authentication/login
accept: */*
Content-Type: application/json

{
  "username": "alex",
  "password": "alexAlex1"
}

> {%
  client.global.set("jwt_token", response.body.token);
%}

### PATCH update user with description and isSearching flag
PATCH http://localhost:8080/api/v1/fyrm/users/69
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "description": "I am Alex",
  "isSearching": "true"
}

### POST create search profile
POST http://localhost:8080/api/v1/fyrm/search-profiles
accept: */*
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "userId": 74,
  "rentPriceLowerBound": 120.0,
  "rentPriceUpperBound": 260.0,
  "latitude": 47.231,
  "longitude": -28.4392,
  "rentMatesGenderOptions": [
    "any"
  ],
  "rentMateCountOptions": [
    "1"
  ],
  "bedroomOptions": [
    "own"
  ],
  "bathroomOptions": [
    "2",
    "> 2"
  ]
}

### GET search profiles by user id
GET http://localhost:8080/api/v1/fyrm/users/74/search-profiles
Accept: application/json
Authorization: Bearer {{jwt_token}}

### DELETE search profile
DELETE http://localhost:8080/api/v1/fyrm/search-profiles/8
Accept: application/json
Authorization: Bearer {{jwt_token}}