openapi: 3.0.1
info:
  title: FYRM Service API docs
  version: 0.0.1
servers:
  - url: /api/v1/fyrm
    description: local

tags:
  - name: account
  - name: authentication

paths:
  '/accounts/name/{name}':
    get:
      parameters:
        - $ref: '#/components/parameters/namePathParameter'
      summary: Filter accounts by name
      operationId: getAccountsByName
      tags:
        - account
      responses:
        '200':
          description: Accounts filtered by name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accounts'
        '422':
          description: Invalid name path parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'

  '/authentication/signup':
    post:
      summary: Sign up user
      operationId: signupUser
      tags:
        - authentication
      requestBody:
        description: Contains sign up information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: Successfully sign up user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Invalid sign up information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'

components:
  schemas:
    BusinessException:
      type: object
      properties:
        code:
          type: string
          description: |
            Indicates a predefined error that can occur.
            * `FIELD_NOT_VALID` - A data transfer object field is invalid
            * `SIGNUP_INFORMATION_NOT_VALID` - Sign up information is invalid

          enum:
            - FIELD_NOT_VALID
            - SIGNUP_INFORMATION_NOT_VALID
        messages:
          type: array
          items:
            type: string
          description: Error messages displayed to the end user.

    Accounts:
      type: array
      items:
        $ref: '#/components/schemas/Account'

    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    SignupRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - role
        - password

    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

  parameters:
    namePathParameter:
      name: name
      in: path
      required: true
      schema:
        type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
