openapi: 3.0.1
info:
  title: FYRM Service API docs
  version: 0.0.1
servers:
  - url: /api/v1/fyrm
    description: local

tags:
  - name: authentication

paths:
  '/authentication/signup':
    post:
      summary: Sign up user
      operationId: signupUser
      tags:
        - authentication
      requestBody:
        description: Contains sign up information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: Successfully sign up user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Invalid sign up information from business perspective.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '422':
          description: Invalid sign up information from validation perspective or email sending mechanism failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'

  '/authentication/login':
    post:
      summary: Log in user
      operationId: loginUser
      tags:
        - authentication
      requestBody:
        description: Contains log in information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully log in user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtLoginResponse'
        '400':
          description: Account is not enabled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '401':
          description: Bad credentials.

  '/authentication/confirm':
    post:
      summary: Confirm user account
      operationId: confirmAccount
      tags:
        - authentication
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: Confirmation code used for enabling the account
      responses:
        '200':
          description: Successfully confirm account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Confirmation code is not associated to any account or it is expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '400':
          description: Confirmation code query parameters misses.

components:
  schemas:
    BusinessException:
      type: object
      properties:
        code:
          type: string
          description: |
            Indicates a predefined error that can occur.
            * `FIELD_NOT_VALID` - A data transfer object field is invalid
            * `SIGNUP_INFORMATION_NOT_VALID` - Sign up information is invalid
            * `LOGIN_FAILED` - Something unexpected happened during log in process
            * `CONFIRMATION_CODE_NOT_VALID` - Confirmation code is not associated to any account or it is expired
            * `EMAIL_SENDING_FAILED` - Confirmation email sending process failed

          enum:
            - FIELD_NOT_VALID
            - SIGNUP_INFORMATION_NOT_VALID
            - LOGIN_FAILED
            - CONFIRMATION_CODE_NOT_VALID
            - EMAIL_SENDING_FAILED
        messages:
          type: array
          items:
            type: string
          description: Error messages displayed to the end user.

    SignupRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - role
        - password

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    JwtLoginResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        token:
          type: string
        tokenType:
          type: string
        username:
          type: string
        email:
          type: string
        role:
          type: string
      required:
        - userId
        - token
        - tokenType
        - username
        - email
        - role

  parameters: { }

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
