openapi: 3.0.1
info:
  title: FYRM Service API docs
  version: 0.0.1
servers:
  - url: /api/v1/fyrm
    description: local

tags:
  - name: authentication
  - name: user
  - name: search-profile

paths:
  '/authentication/signup':
    post:
      summary: Sign up user
      operationId: signupUser
      tags:
        - authentication
      requestBody:
        description: Contains sign up information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: Successfully sign up user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Invalid sign up information from business perspective.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '422':
          description: Invalid sign up information from validation perspective or email sending mechanism failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'

  '/authentication/login':
    post:
      summary: Log in user
      operationId: loginUser
      tags:
        - authentication
      requestBody:
        description: Contains log in information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully log in user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtLoginResponse'
        '400':
          description: Account is not enabled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '401':
          description: Bad credentials.

  '/authentication/confirmationcode/resend':
    post:
      summary: Resend confirmation code
      operationId: resendConfirmationCode
      tags:
        - authentication
      requestBody:
        description: Contains user id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationCodeRequest'
      responses:
        '204':
          description: Successfully resent confirmation code.
        '400':
          description: User does not exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'

  '/authentication/confirm':
    post:
      summary: Confirm user account
      operationId: confirmAccount
      tags:
        - authentication
      requestBody:
        description: Contains user id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmAccountRequest'
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: Confirmation code used for enabling the account
      responses:
        '200':
          description: Successfully confirm account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '422':
          description: Confirmation code is not associated to any account or it is expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessException'
        '400':
          description: Confirmation code query parameters misses.

  '/users/{userId}':
    parameters:
      - $ref: '#/components/parameters/userIdPathParameter'
    patch:
      summary: Updates user identified by id
      operationId: updateUser
      requestBody:
        description: Contains updated user information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      tags:
        - user
      responses:
        '200':
          description: Successfully updated user
        '404':
          $ref: '#/components/responses/NotFound'

  '/search-profiles':
    post:
      summary: Create search profile
      operationId: createSearchProfile
      tags:
        - search-profile
      requestBody:
        description: Contains search profile information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchProfile'
      responses:
        '201':
          description: Search profile successfully created.
        '401':
          description: Unauthorized.

components:
  schemas:
    BusinessException:
      type: object
      properties:
        code:
          type: string
          description: |
            Indicates a predefined error that can occur.
            * `FIELD_NOT_VALID` - A data transfer object field is invalid
            * `SIGNUP_INFORMATION_NOT_VALID` - Sign up information is invalid
            * `LOGIN_FAILED` - Something unexpected happened during log in process
            * `CONFIRMATION_CODE_NOT_VALID` - Confirmation code is not associated to any account or it is expired
            * `EMAIL_SENDING_FAILED` - Confirmation email sending process failed
            * `RESOURCE_NOT_FOUND` - Resource not found

          enum:
            - FIELD_NOT_VALID
            - SIGNUP_INFORMATION_NOT_VALID
            - LOGIN_FAILED
            - CONFIRMATION_CODE_NOT_VALID
            - EMAIL_SENDING_FAILED
            - RESOURCE_NOT_FOUND
        messages:
          type: array
          items:
            type: string
          description: Error messages displayed to the end user.

    SignupRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - role
        - password

    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    ConfirmAccountRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
      required:
        - userId

    ResendConfirmationCodeRequest:
      type: object
      properties:
        userId:
          type: integer
          format: int64
      required:
        - userId

    SignupResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        email:
          type: string
        message:
          type: string
      required:
        - userId
        - email
        - message

    JwtLoginResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        token:
          type: string
        tokenType:
          type: string
        username:
          type: string
        email:
          type: string
        role:
          type: string
        birthDate:
          type: string
        description:
          type: string
        isSearching:
          type: boolean
      required:
        - userId
        - token
        - tokenType
        - username
        - email
        - role
        - birthDate
        - description
        - isSearching

    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    UpdateUser:
      type: object
      properties:
        description:
          type: string
        isSearching:
          type: boolean
      required:
        - description
        - isSearching

    SearchProfile:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        rentPriceLowerBound:
          type: number
          format: double
        rentPriceUpperBound:
          type: number
          format: double
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        rentMatesGenderOptions:
          type: array
          items:
            type: string
        rentMateCountOptions:
          type: array
          items:
            type: string
        bedroomOptions:
          type: array
          items:
            type: string
        bathroomOptions:
          type: array
          items:
            type: string
      required:
        - userId
        - rentPriceLowerBound
        - rentPriceUpperBound
        - latitude
        - longitude
        - rentMatesGenderOptions
        - rentMateCountOptions
        - bedroomOptions
        - bathroomOptions

  parameters:
    userIdPathParameter:
      name: userId
      description: User id
      in: path
      required: true
      schema:
        type: integer
        format: int64

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
