name: super-linter

on:
  push:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      - uses: dbelyaev/action-checkstyle@v0.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
      - name: Lint codebase
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          VALIDATE_XML: true
          VALIDATE_YAML: true